### ISSUE TITLE
Special markers & Flags

### ISSUE THREAD

**Issue by 3F** [3F/regXwild#3]
To use additional syntax, we can add special markers & flags

The entry point like: 

* Single: `@x ...`
* Pair: `@x ... @`

Where `x` the any supported combination, like single symbol [0-9a-z] or complex expressions like `{1,7}`. 

This related for #1 (v2 - markers via flags), but the main idea to extend syntax for support additional features like the following below.

## Sub-Issues

- [ ] #4 - Capture data for all quantifiers
- [ ] #5 - Control of newline symbols
- [ ] #1 - Disable Meta-Symbols
 

## Special symbol-logic like for current '>'

`MS_ANYSP    = _T('>'), // as [^/]*  //TODO: >\>/ i.e. '>' + {symbol}`

* `@B>` ...

## etc.
